#!/bin/bash

PEM=$( echo $PRIV_KEY )
GITHUB_APP_ID=198558 # Whatever your github app id is

NOW=$( date +%s )
IAT="${NOW}"
EXP=$((${NOW} + 120))
HEADER_RAW='{"alg":"RS256","typ":"JWT"}'
HEADER=$( echo -n "${HEADER_RAW}" | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n' )
PAYLOAD_RAW='{"iat":'"${IAT}"',"exp":'"${EXP}"',"iss":'"${GITHUB_APP_ID}"'}'
PAYLOAD=$( echo -n "${PAYLOAD_RAW}" | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n' )
HEADER_PAYLOAD="${HEADER}"."${PAYLOAD}"
SIGNATURE=$( openssl dgst -sha256 -sign <(echo -n "${PEM}") <(echo -n "${HEADER_PAYLOAD}") | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n' )
JWT="${HEADER_PAYLOAD}"."${SIGNATURE}"

echo "::echo:off"
echo "::set-output name=GH_JWT::${JWT}"
