name: GHA token generator
on:
  schedule:
    - cron: '5,20 * * * 1-5'
  workflow_dispatch:  

jobs:
  gen-jwt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Generate JWT & Update app token.
        id: gen-jwt
        run: ' ./.github/genjwt '
        env:
          PRIV_KEY: ${{ secrets.GH_APP_PEM_KEY }}
          APP_ID: ${{ secrets.GH_APPID }}
          PAT: ${{ secrets.GH_PAT }} # Expires on Sat, Aug 6 2022.
          REPO_PUBLIC_KEY: ${{ secrets.SECRET_PUBLIC_KEY }}
          KEY_ID: ${{ secrets.SECRET_PUBLIC_KEY_ID }}
