name: GHA token generator
on:
  schedule:
    - cron: '5,20 * * * 1-5'
  workflow_dispatch:  

jobs:
  gen-jwt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      - name: Generate JWT & Update app token.
        id: gen-jwt
        run: ' ./.github/genjwt '
        env:
          PRIV_KEY: ${{ secrets.GH_APP_PEM_KEY }}
          APP_ID: ${{ secrets.GH_APPID }}
          PAT: ${{ secrets.GH_PAT_BETA }} 
          REPO_PUBLIC_KEY: ${{ secrets.SECRET_PUBLIC_KEY }}
          KEY_ID: ${{ secrets.SECRET_PUBLIC_KEY_ID }}
